export default function Head() {
  return (
    <>
      <title>S. M. Imtiaz</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="https://i.ibb.co/hVb3LYG/VJko-UZ0e-g.jpg" />
    </>
  );
}
